// let's imagine this file is autogenerated from the backend

// ideally, we want to keep these api related types in sync
// with the backend instead of manually writing them out

type BaseEntity = {
	id: string | number;
	createdAt?: Date;
	updatedAt?: Date;
}

export type Entity<T> = {
	[K in keyof T]: T[K];
} & BaseEntity;

export type PaginatedResponse<T> = {
	data: T[];
	meta: {
		pageIndex: number;
		pageSize: number;
		count: number;
	}
}