import { ReactNode } from "react";
import type { Metadata } from "next";
import USearchWithFilterWrapper from "@/components/shared/search/USearchWithFilterWrapper";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function StudentLayout({
    children,
}: Readonly<{
    children: ReactNode;
}>) {
    return (
        <div className="relative">
            <div className="w-full mx-auto pb-10 relative">
                <div className="flex justify-center sticky top-0 bottom-0 left-0 z-10 w-full py-5 bg-gray-100">
                    <div className="w-full mx-auto max-w-5xl">
                        <USearchWithFilterWrapper dropdownData={null} />
                    </div>
                </div>
                <div className="mt-8 w-fit mx-auto">{children}</div>
            </div>
        </div>
    );
}
