import { ReactNode } from "react";
import type { Metadata } from "next";
import USearchWithFilterWrapper from "@/components/shared/search/USearchWithFilterWrapper";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function StudentLayout({
    children,
}: Readonly<{
    children: ReactNode;
}>) {
    return (
        <>
            <div className="w-fit mx-auto py-10">{children}</div>
        </>
    );
}
